version: "3.9"

services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    ports:
      - "8080:8080"
      - "50051:50051"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    depends_on:
      - scrapper
    ports:
      - "8082:8082"
      - "50052:50052"