FROM golang:1.25.6-alpine AS build
WORKDIR /src
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/scrapper ./cmd/scrapper

FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata
COPY --from=build /out/scrapper /app/scrapper
COPY app.env /app/app.env
ENV TZ=Europe/Riga
EXPOSE 8080 50051
ENTRYPOINT ["/app/scrapper"]