version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: link-tracker-postgres
    environment:
      POSTGRES_DB: link_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d link_tracker" ]
      interval: 5s
      timeout: 5s
      retries: 10
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50051:50051"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    depends_on:
      - scrapper
    ports:
      - "8082:8082"
      - "50052:50052"
volumes:
  postgres_data: