services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    environment:
      SCRAPPER_ADDR_GRPC: "0.0.0.0:50051"
      SCRAPPER_ADDR_HTTP: "0.0.0.0:8080"
      BOT_ADDR_GRPC: "bot:50052"
      MINUTES_INTERVAL_CHECK: "1"
      GITHUB_TOKEN: ""
      STACK_OVERFLOW_KEY: ""
    ports:
      - "18080:8080"
      - "15051:50051"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    working_dir: /app
    volumes:
      - ./app.env:/app/app.env:ro
    depends_on:
      - scrapper
    environment:
      APP_TELEGRAM_TOKEN: "dummy"
      SCRAPPER_ADDR_GRPC: "scrapper:50051"
      BOT_ADDR_GRPC: "0.0.0.0:50052"
      BOT_ADDR_HTTP: "0.0.0.0:8082"
      BOT_DISABLE_TELEGRAM: "true"
    ports:
      - "18082:8082"
      - "15052:50052"