// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source usecase.go -package scrapper_app -destination usecase_mock.go
//

// Package scrapper_app is a generated GoMock package.
package scrapper_app

import (
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
	isgomock struct{}
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatRepository) CreateChat(ID int64) (*domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ID)
	ret0, _ := ret[0].(*domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatRepositoryMockRecorder) CreateChat(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatRepository)(nil).CreateChat), ID)
}

// DeleteChatByID mocks base method.
func (m *MockChatRepository) DeleteChatByID(ID int64) (*domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChatByID", ID)
	ret0, _ := ret[0].(*domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteChatByID indicates an expected call of DeleteChatByID.
func (mr *MockChatRepositoryMockRecorder) DeleteChatByID(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChatByID", reflect.TypeOf((*MockChatRepository)(nil).DeleteChatByID), ID)
}

// GetChatByID mocks base method.
func (m *MockChatRepository) GetChatByID(ID int64) (*domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByID", ID)
	ret0, _ := ret[0].(*domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByID indicates an expected call of GetChatByID.
func (mr *MockChatRepositoryMockRecorder) GetChatByID(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByID", reflect.TypeOf((*MockChatRepository)(nil).GetChatByID), ID)
}

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLinkRepository) CreateLink(ChatID int64, URL string, Tags, Filters []string) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ChatID, URL, Tags, Filters)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkRepositoryMockRecorder) CreateLink(ChatID, URL, Tags, Filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkRepository)(nil).CreateLink), ChatID, URL, Tags, Filters)
}

// DeleteLink mocks base method.
func (m *MockLinkRepository) DeleteLink(ChatID int64, URL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ChatID, URL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkRepositoryMockRecorder) DeleteLink(ChatID, URL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkRepository)(nil).DeleteLink), ChatID, URL)
}

// GetLinksByChatID mocks base method.
func (m *MockLinkRepository) GetLinksByChatID(ChatID int64) ([]*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinksByChatID", ChatID)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinksByChatID indicates an expected call of GetLinksByChatID.
func (mr *MockLinkRepositoryMockRecorder) GetLinksByChatID(ChatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinksByChatID", reflect.TypeOf((*MockLinkRepository)(nil).GetLinksByChatID), ChatID)
}
