// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source usecase.go -package botapp -destination usecase_mock.go
//

// Package botapp is a generated GoMock package.
package botapp

import (
	context "context"
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBotRepository is a mock of BotGateway interface.
type MockBotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBotRepositoryMockRecorder
	isgomock struct{}
}

// MockBotRepositoryMockRecorder is the mock recorder for MockBotRepository.
type MockBotRepositoryMockRecorder struct {
	mock *MockBotRepository
}

// NewMockBotRepository creates a new mock instance.
func NewMockBotRepository(ctrl *gomock.Controller) *MockBotRepository {
	mock := &MockBotRepository{ctrl: ctrl}
	mock.recorder = &MockBotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotRepository) EXPECT() *MockBotRepositoryMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockBotRepository) GetMessages(ctx context.Context, timeoutSec int) (<-chan domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, timeoutSec)
	ret0, _ := ret[0].(<-chan domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockBotRepositoryMockRecorder) GetMessages(ctx, timeoutSec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockBotRepository)(nil).GetMessages), ctx, timeoutSec)
}

// SendMessage mocks base method.
func (m *MockBotRepository) SendMessage(chatID int64, replyToMessageID int, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", chatID, replyToMessageID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockBotRepositoryMockRecorder) SendMessage(chatID, replyToMessageID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockBotRepository)(nil).SendMessage), chatID, replyToMessageID, text)
}
