// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/bot.proto

package pbv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdateLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateLinkRequestMultiError, or nil if none found.
func (m *UpdateLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 0 {
		err := UpdateLinkRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUrl()) < 1 {
		err := UpdateLinkRequestValidationError{
			field:  "Url",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetUrl()); err != nil {
		err = UpdateLinkRequestValidationError{
			field:  "Url",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := UpdateLinkRequestValidationError{
			field:  "Url",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	if len(m.GetTgChatIds()) < 1 {
		err := UpdateLinkRequestValidationError{
			field:  "TgChatIds",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateLinkRequestMultiError(errors)
	}

	return nil
}

// UpdateLinkRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateLinkRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateLinkRequestMultiError) AllErrors() []error { return m }

// UpdateLinkRequestValidationError is the validation error returned by
// UpdateLinkRequest.Validate if the designated constraints aren't met.
type UpdateLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateLinkRequestValidationError) ErrorName() string {
	return "UpdateLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateLinkRequestValidationError{}

// Validate checks the field values on UpdateLinkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateLinkResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateLinkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateLinkResponseMultiError, or nil if none found.
func (m *UpdateLinkResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateLinkResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateLinkResponseMultiError(errors)
	}

	return nil
}

// UpdateLinkResponseMultiError is an error wrapping multiple validation errors
// returned by UpdateLinkResponse.ValidateAll() if the designated constraints
// aren't met.
type UpdateLinkResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateLinkResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateLinkResponseMultiError) AllErrors() []error { return m }

// UpdateLinkResponseValidationError is the validation error returned by
// UpdateLinkResponse.Validate if the designated constraints aren't met.
type UpdateLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateLinkResponseValidationError) ErrorName() string {
	return "UpdateLinkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateLinkResponseValidationError{}
